language: java
addons:
    apt:
        packages:
            - cpanminus
            - perl
before_install:
    - cd DBD-JDBC && cpanm --installdeps .
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
sudo: false      
