language: java
addons:
    apt:
        packages:
            - cpanminus
            - perl
before_install:
    - cpanm --cpanfile DBD-JDBC/.cpanfile --installdeps .
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
sudo: false      
