language: java
before_install:
    - sudo apt-get update 
    - sudo apt-get install cpanminus perl
    - cpanm --cpanfile DBD-JDBC/.cpanfile --installdeps .
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
