language: java
before_install:
    - sudo apt-get update 
    - sudo apt-get install cpanminus perl
    - cpanm --installdeps --notests DBD-JDBC
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
