language: java
env:
    - PERL_CPANM_OPT="--local-lib=~/perl5" PERL5LIB="~/perl5:~/perl5/lib/perl5:$PERL5LIB"
addons:
    apt:
        packages:
            - cpanminus
            - perl
before_install:
    - (cd DBD-JDBC && cpanm -v --notest --installdeps .)
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
sudo: false      
