language: java
before_install:
    - sudo apt-get update 
    - sudo apt-get install cpanminus perl
    - cpanm --installdeps Convert::BER XML::Simple DBI
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
