language: java
env:
    - PERL_CPANM_OPT="--local-lib=$HOME/perl5" PERL5LIB="$HOME/perl5:$HOME/perl5/lib:$HOME/perl5/lib/perl5:$PERL5LIB"
addons:
    apt:
        packages:
            - cpanminus
            - perl
before_install:
    - ./setup.sh
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk6
sudo: false      
